project_id = "training-area-bot"

[api]
enabled = true

[db]
port = 54322
shadow_port = 54323
major_version = 15

[studio]
port = 54323

[functions]
port = 54321

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/callback"]
