apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
  labels:
    app: bot-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
        - name: bot-service
          image: ghcr.io/example/bot-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: supabase-url
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: supabase-anon-key
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
