services:
  - type: web
    name: training-area-bot
    env: node
    plan: starter
    buildCommand: echo "No build step required"
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    autoDeploy: true
